### ISSUE TITLE
“rustc” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by xlc** [paritytech/rustc-rv32e-toolchain#26]
<img width="245" alt="Screenshot 2024-04-30 at 10 39 09 PM" src="https://github.com/paritytech/rustc-rv32e-toolchain/assets/1201310/26a8b06f-5074-485e-9677-12806b0454bd">

I guess some signing will be needed for prebuild version?

**Comment by athei** [comment]
Updated the README in the linked branch. Please check if that works for you.

**Comment by xlc** [comment]
I won't try it as I figured that I shouldn't run unsigned binary from internet on my main dev machine

**Comment by athei** [comment]
It's not like the binaries downloaded by rustup are signed. Compiling code from the internet is also not really safe. Could have snuck some sneaky build.rs in there :)

Not really trying to convince you here, though. I am glad for everybody building from source and bringing up issues like you did.
